changelog:
  exclude:
    labels:
      - no-releasenotes
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🪲 Bug Fixes
      labels:
        - bug
    - title: 🏎️ Performance
      labels:
        - performance
    - title: 🧹 Refactors
      labels:
        - refactor
    - title: 📚 Documentation
      labels:
        - documentation
    - title: 🧪 Tests
      labels:
        - test
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🛠️ Build & CI
      labels:
        - build
        - ci
    - title: 🧽 Chore
      labels:
        - chore
    - title: 🫶 Other Changes
      labels:
        - "*"
