name: building

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install Ragel 6.10
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ragel

      - name: Build the parser
        run: make

      - name: Ensure the parser code is updated
        run: git diff --exit-code
