name: building

on:
  push:
    branches: ['ci/build-workflow']
  pull_request:
    branches: ['ci/build-workflow']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Restore the Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Install Ragel 6.10
        run: sudo apt-get install -y ragel

      - name: Build the parser
        run: make

      - name: Ensure the parser code is updated
        run: git diff --exit-code