name: linting

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .golangci.yml
      - .github/workflows/lint.yml
    branches: ['develop']
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .golangci.yml
      - .github/workflows/lint.yml
    branches: ['develop']

permissions:
  contents: read

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.4
