name: linting

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .golangci.yml
      - .github/workflows/lint.yml
    branches: ['develop']
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .golangci.yml
      - .github/workflows/lint.yml
    branches: ['develop']

permissions:
  contents: read

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.24'
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7.0.1
        with:
          version: v2.11.4
